### ISSUE TITLE
Annu Rev Neuro '16 | Correlations and Neuronal Population Information.

### ISSUE THREAD

**Issue by NorbertZheng** [NorbertZheng/read-papers#9]
https://www.annualreviews.org/doi/abs/10.1146/annurev-neuro-070815-013851

**Comment by Fassial** [comment]
neuron群体的spike活动是相互协调的（coordinated），就是每个neuron的spike活动都会受到其它neuron的spike活动影响，产生看似极为复杂的活动模式。
一种广泛关注的协调（coordination）方式神经元对之间的关系——相关性（correlation）。当然，这是一个极端的协调关系简化，只考虑两两之间的协调关系。这样一种二阶统计结构不太可能完全捕捉到neuron群体丰富的活动模式。但是相关性又是极其有用的，因为其对neuron群体编码有很大的影响，特别是生物合理算法（简单线性等）可以提取的那一部分信息。

**Comment by Fassial** [comment]
### Correlations and Information: A Brief Introduction
尽管单个neuron的variability限制了它们提供的有关外部刺激的信息，但如果每个neuron的variability是相互独立的，则可以通过汇集或平均许多神经元的反应以达到对stimulus的精确估计。
但就算有noise correlation又如何（每个neuron的variability相关），并不影响它们的可分性，可能并不会影响对于认知层次的判定（因为如果能做出对应的behavior，带有noise的neuron表征必然是可分的），只是可能会影响其表征几何的一些性质。这个问题在#8 中也有探讨，但是还是无法解决noise相关的问题。
![image](https://user-images.githubusercontent.com/37235023/137726288-35bdeb9e-229d-428d-9f09-fdaacc397454.png)

**Comment by Fassial** [comment]
但说实在，就算有noise correlation，在高维空间中，不同trial的点还是分布在一块，毕竟这是下游behavior相关脑区所要读取的信息，总归是可分的（不论是线性可分还是非线性可分）。那么对于decision-making任务，不同task的表征分布是一个高维流形，这个高维流形是某个时间点分布随时间的延申。只要noise correlation不会影响到高维表征空间中各个流形的可分性，不都没有问题么？生物的算法也不一定是linear的啊，多层网络堆积在一块这怎么会是一个线性的呢？

**Comment by Fassial** [comment]
为了定量linear decoder的acc，我们可以考虑linear FI度量。linear FI度量的是optimal linear decoder对于stimulus的最小可分性，更高的linear FI表示optimal linear decoder估计的更少variance，定义如下：
![image](https://user-images.githubusercontent.com/37235023/137835982-31e0ad20-1a65-43fb-87ae-af3f4cd7502b.png)
这里的f'是tuning func（就是optimal linear decoder的func）的一阶导数，其为随stimulus变化时response的平均变化；Q是表征反应Cov矩阵，其是由多次stimulus多次trial的神经表征矩阵计算而来，但是这里应该是默认了stimulu-independent（本来Cov矩阵只能依据同一stimulus多次展现，计算spike count的相关性），也就是Q是由跨trial表征矩阵（n_neuron x n_trial）计算而来。

**Comment by Fassial** [comment]
#### Linear Fisher Information for Fine and Coarse Discrimination
---
在经典的分类任务中，受试被要求区分两个相似的stimulus：
![image](https://user-images.githubusercontent.com/37235023/137842426-fcf6c4b9-57f5-43a4-b427-6e07bbf029fc.png)
依据neuron群体反应，我们可以构建一个对两个stimulus无偏的估计器，LOLE（locally optimal linear estimator）：
![image](https://user-images.githubusercontent.com/37235023/137842690-3e944f36-621c-486e-a124-71ec32109f02.png)
这就是给定神经表征r，所推测的对应stimulus。这里的f'是tuning func的差分值，Q是stimulus-avg的neuron Cov矩阵（看来是直接默认stimulus-independent了。
![image](https://user-images.githubusercontent.com/37235023/137842995-916ea8f4-f7fc-406a-9e1d-6c82b74eb523.png)
而linear FI的定义如下：
![image](https://user-images.githubusercontent.com/37235023/137843062-3d9dec56-2769-47b0-a866-cc3d70a6fa68.png)
这里的Var表示给定stimulus种类后，neuron群体会产生一个r分布，将该r分布输入LOLE中，得到估计stimulus分布的Var。二分类是一个很简单的问题，必然会有unbiased的解，这也就说明我们永远可以显式地写出linear FI，而不像full FI可能不一定能得到。
上述 LOLE 的定义和linear FI的表达式并没有假设`ds`很小，它对精细和粗略的区分都有效。

**Comment by Fassial** [comment]
Abbott & Dayan探究了correlation对于FI的影响。对于homogeneous的neuron群体，FI会被局部强correlation（limited-range correlation）所降低。更准确地说，不仅被降低了，还会饱和，即FI随着neuron群体size的增大而收敛到一个值。大量实验证据表明大脑皮层中的correlation具备limited-range correlation结构，如V1、MT等。

**Comment by Fassial** [comment]
Moreno-Bote等人在2014年的一篇工作中发现，影响information的response Cov中的那一部分与tuning funcs的一阶导数有关系，或者说是正比于tuning func的一阶导数乘积。有这种结构的correlation被称为differential correlation。而上面，limited-range correlation之所以可以让homogeneous的neuron群体饱和就是因为其内部包含differential correlation。
现在我们考虑一个观测者正在进行感知任务——辨别stimulus的角度。如果每个trial，我们对stimulus进行角度上微小的扰动，这样便会人工地损伤受试者的表现性能。这是因为我们对stimulus的操控会以一种被tuning func一阶导数预测的方式影响orientation-selective神经元的response。
或者，通俗一点的情况是，我们将stimulus固定，而neuron的response会在trial-by-trail时变化。而限制性能的variability是那种可以造成和外界stimulus可变性相同方式的震荡。在神经表征流形上来说就是，体现在流形方向上的variability会限制linear FI，但如果variablility在正交于流形的方向上，则不会影响linear FI。
![image](https://user-images.githubusercontent.com/37235023/137941779-ee13aa05-e154-46a6-8090-21c23d39726f.png)

**Comment by Fassial** [comment]
虽然differential correlation会导致information饱和，但它们在overall correlation中的占比有可能很小，可以忽略。因此，直接测量correlation与tuning func一阶导数之间的关系并不能很准确地评估differential correlation的影响。补充的评估方法有：
 - 检验随着neuron数量增加，information是否饱和。
 - 检查动物的行为报告与试验中单个神经元的波动之间的关系。

使用第二种方法，Pitkow等人发现vestibular areas使用了一种包含了differential correlation的编码。

**Comment by Fassial** [comment]
尽管differential correlation会导致information饱和，sensory群体的总information也可以被nondifferential correlation（与tuning func一阶导数无关的correlation）影响。考虑一群noise dist相互独立的neuron群体，增加neuron数量会导致information增长，没有边界。这一描述同样适用于带有某类nondifferential correlation（比如uniform additive noise）的heterogeneous神经元群体，只是增长幅度稍微小一些，也会让information降低。然而，differential correlation会有更大的影响——使information相比于independent的编码随着neuron数目的增加而降为0。因此，nondifferential correlation会在两个程度上影响：
 - 在small群体数量的时候，强烈影响information，相比于independent noise dist的斜率降低。
 - 在large群体数量的时候，通过与differential correlation相互作用，影响information的饱和点。

![image](https://user-images.githubusercontent.com/37235023/137946939-65f0cc65-50f0-404d-b4a7-8ae95ee28509.png)

**Comment by Fassial** [comment]
Estimating Linear Fisher Information
___

**Comment by Fassial** [comment]
于是，这样就产生了一个悖论：information只能通过所能记录的neuron群体来测量它，但是correlation对这些群体的影响可能与其对更大、功能更相关的neuron群体影响ratio不同。这里考虑的问题，其实就是#5 中考虑的所记录neuron表征几何失真度的问题，我们需要更多的neuron记录、依据我们所记录数据进行正确推断的理论依据（这就是#5 所部分解决的）以及对任务相关neuron数量的先验了解。
目前，尚不清楚记录的相关性变化（例如行为或刺激操作发生的变化）是否对人口信息产生有意义的影响。

**Comment by Fassial** [comment]
当然，前面的decorrelate只是为了有效编码，并不可能完全消除所有correlation。对于接收有限信息（即，比 N 个独立神经元群体可获得的信息少）的网络，完全去相关将使信息随网络规模线性增长，从而超过输入中的信息。 这将违反数据处理不等式，即处理信号不能增加其信息。输入信息随种群规模线性增长，循环网络实现的完全去相关（在无限大种群的限制下）相当于保留所有输入信息。
